### ISSUE TITLE
Add some new tests.

### ISSUE THREAD

**Issue by btimby** [smartfile/client-node#47]
Some upstream tests failed due to bugs in `client-node`. Add tests to catch these bugs earlier. These bugs are fixed now in the commits provided. But to avoid future headache, add some (passing) tests for these.

- Add a test for authentication failure.
https://github.com/smartfile/client-node/pull/46/commits/aba4366a7e25c750dca6ce0556b578285c96bdee

This one failed because `/whoami` did not return an error to callback. Add a test for login failure (we have one for success).

- Add a test for `create*Stream()` without options.
https://github.com/smartfile/client-node/pull/46/commits/2f2632ba89ed55a6f6ec4d8daf75823ffd1344dd
https://github.com/smartfile/client-node/pull/46/commits/27d39f9b18a379e96f29b7f2fd476c97dc6eda21

These failed because the functions assume `options` would be defined. Add tests to make sure these work when `options` is omitted.

**Comment by cabarnes** [comment]
Isn't this already testing `createWriteStream` without options? https://github.com/smartfile/client-node/blob/master/tests/test_fs.js#L243
